import { NavItem } from "@/types";
export const navItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/",
    icon: "dashboard",
    label: "home",
    isProcted: false,
  },
  {
    title: "Inbox",
    href: "/inbox",
    icon: "layers",
    label: "layers",
    isProcted: false,
  },
  {
    title: "Members",
    href: "/member",
    icon: "user",
    label: "user",
    isProcted: false,
  },
  {
    title: "Departments",
    href: "/departments",
    icon: "box",
    label: "employees",
    isProcted: false,
  },
  {
    title: "Groups",
    href: "/groups",
    icon: "group",
    label: "profile",
    isProcted: true,
  },
  {
    title: "Events",
    href: "/events",
    icon: "calendar",
    label: "kanban",
    isProcted: true,
  },
  {
    title: "Followup",
    href: "/followup",
    icon: "reader",
    label: "kanban",
    isProcted: true,
  },
  {
    title: "Appointments",
    href: "/appointments",
    icon: "clock",
    label: "kanban",
    isProcted: true,
  },
  {
    title: "Reports",
    href: "/analytics",
    icon: "file",
    label: "Inbox",
    tag: "Soon",
    isProcted: true,
    // count: 5, // Example count
  },
  {
    title: "contribution",
    href: "/contribution",
    icon: "billing",
    label: "addetails",
    tag: "Soon",
    isProcted: true,
  },
  {
    title: "Settings",
    href: "/settings",
    icon: "settings",
    label: "settings",
    isProcted: true,
  },
];
